- 👋 Hi, I’m @Jonenza
- 👀 I’m interested in coding,gaming and IT
- 🌱 I’m currently learning python and java
- 💞️ I’m looking to collaborate on ...
- 📫 How to reach me https://t.me/pastaconilragu - https://twitter.com/AgenteJonenza - https://discord.com/users/503540375743627266 -
